CREATE TABLE image_quality_reviews (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  image_id BIGINT NOT NULL,
  workflow_run_id VARCHAR(64) NULL,
  workflow_type VARCHAR(64) NULL,
  workflow_step VARCHAR(64) NULL,
  review_source VARCHAR(32) NOT NULL DEFAULT 'coze_workflow',
  review_status VARCHAR(32) NOT NULL DEFAULT 'pending',
  quality_status VARCHAR(32) NULL,
  confidence DECIMAL(5,4) NULL,
  vlm_scores JSON NULL,
  reject_reasons JSON NULL,
  suggested_action VARCHAR(32) NULL,
  prompt_trace JSON NULL,
  reference_images JSON NULL,
  reference_image_hashes JSON NULL,
  candidate_image_url TEXT NULL,
  constraint_preset VARCHAR(64) NULL,
  inputs_snapshot JSON NULL,
  human_decision VARCHAR(32) NULL,
  human_reject_reason TEXT NULL,
  human_reviewer VARCHAR(128) NULL,
  coze_workflow_run_id VARCHAR(128) NULL,
  raw_trace_url TEXT NULL,
  error_code VARCHAR(128) NULL,
  error_message TEXT NULL,
  retry_count INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  started_at DATETIME NULL,
  finished_at DATETIME NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_quality_reviews_image_id (image_id),
  INDEX idx_quality_reviews_workflow_run (workflow_run_id),
  INDEX idx_quality_reviews_review_status (review_status),
  INDEX idx_quality_reviews_quality_status (quality_status),
  INDEX idx_quality_reviews_created_at (created_at)
);
